import bcrypt from 'bcryptjs';

const data = {
    users: [
      {
        name: 'Basir',
        email: 'admin@example.com',
        password: bcrypt.hashSync('1234', 8),
        isAdmin: true,
      },
      {
        name: 'John',
        email: 'user@example.com',
        password: bcrypt.hashSync('1234', 8),
        isAdmin: false,
      },
    ],

    products: [
      {
        name: 'Nike Slim Shirt',
        category: 'Shirts',
        image: '/images/i1.jpg',
        price: 120,
        brand: 'Nike',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
        countInStock: 5,
      },
      {
        name: 'Lacoste Free Shirt',
        category: 'Shirts',
        image: '/images/i2.jpg',
        price: 220,
        brand: 'Lacoste',
        rating: 4.8,
        numReviews: 17,
        description: 'high quality product',
        countInStock: 5,
      },
      {
        name: 'Nike Slim Pant',
        category: 'Pants',
        image: '/images/i2.jpg',
        price: 78,
        brand: 'Nike',
        rating: 4.5,
        numReviews: 14,
        description: 'high quality product',
        countInStock: 5,
      },
      {
        name: 'Puma Slim Pant',
        category: 'Pants',
        image: '/images/i3.jpg',
        price: 65,
        brand: 'Puma',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
        countInStock: 5,
      },
      {
        name: 'Adidas Fit Pant',
        category: 'Pants',
        image: '/images/i3.jpg',
        price: 139,
        brand: 'Adidas',
        rating: 4.5,
        numReviews: 15,
        description: 'high quality product',
        countInStock: 5,
      },
      {
        name: 'Adidas Fit Pant',
        category: 'Pants',
        image: '/images/i3.jpg',
        price: 139,
        brand: 'Adidas',
        rating: 4.5,
        numReviews: 15,
        description: 'high quality product',
        countInStock: 0,
      },
    ],
  };
  export default data;